-- Baseline Flyway (issue #139) : capture du schema PostgreSQL actuel tel que
-- produit jusqu'ici par Hibernate (spring.jpa.hibernate.ddl-auto=update), pour
-- les 11 entites JPA existantes (7 modules : auth, equipement, alerte, seuil,
-- metrique, audit, rapport). A partir de cette version, le schema n'evolue
-- plus que par migrations Flyway versionnees (V2, V3, ...) ; ddl-auto passe a
-- "validate".
--
-- Genere par bootstrap Hibernate pur (MetadataSources + SchemaManagementTool,
-- sans connexion a une base reelle : pas de Postgres accessible dans
-- l'environnement d'edition) a partir du mapping JPA actuel des entites,
-- verifie manuellement contre chaque @Table/@Column/@JoinColumn. NE COUVRE
-- PAS TimescaleDB (hypertable/continuous aggregates/retention sur
-- "metriques") : cf. issue #56, non implementee a ce jour malgre son etat
-- "closed" sur GitHub (cf. commentaires de suivi sur #56 et #57) - cette
-- baseline reste donc du PostgreSQL standard, sans extension. Le passage a
-- TimescaleDB, une fois #56 reellement traite, se fera via une migration
-- ulterieure (Vn__timescaledb.sql) qui convertira "metriques" en hypertable.

-- === auth ===

create table app_users (
    id bigint generated by default as identity,
    username varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    role varchar(255) not null
        check (role in ('ADMINISTRATEUR', 'TECHNICIEN', 'OBSERVATEUR')),
    user_type varchar(255) not null
        check (user_type in ('INDIVIDUAL', 'BUSINESS', 'PARTNER')),
    active boolean not null,
    notifications_email boolean not null default true,
    failed_login_attempts integer not null,
    locked_until timestamp(6),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table refresh_tokens (
    id uuid not null,
    token varchar(255) not null unique,
    app_user_id bigint not null,
    expiry_date timestamp(6) not null,
    revoked boolean not null,
    created_at timestamp(6) not null,
    primary key (id)
);

create table password_reset_tokens (
    id uuid not null,
    token varchar(255) not null unique,
    app_user_id bigint not null,
    expiry_date timestamp(6) not null,
    used boolean not null,
    created_at timestamp(6) not null,
    primary key (id)
);

-- === equipement ===

create table equipements (
    id uuid not null,
    nom varchar(150) not null,
    adresse_ip varchar(45) not null unique,
    type varchar(30) not null
        check (type in ('SERVEUR', 'ROUTEUR', 'SWITCH', 'POINT_ACCES')),
    localisation varchar(150),
    etat varchar(30) not null
        check (etat in ('ACTIF', 'INACTIF', 'EN_MAINTENANCE')),
    description text,
    cle_api varchar(255),
    depend_de_id uuid,
    derniere_mesure timestamp(6),
    primary key (id)
);

-- === metrique ===

create table metriques (
    id bigint generated by default as identity,
    equipement_id uuid not null,
    type_metrique varchar(30) not null
        check (type_metrique in (
            'CPU', 'RAM', 'DISQUE', 'SWAP', 'NOMBRE_PROCESSUS', 'PORTS_ECOUTE',
            'DISQUE_IO_LECTURE', 'DISQUE_IO_ECRITURE', 'RESEAU_IO_ENTRANT',
            'RESEAU_IO_SORTANT', 'UPTIME', 'CHARGE_1MIN', 'RAM_TOTALE_MO',
            'RAM_UTILISEE_MO', 'DISQUE_TOTAL_GO', 'DISQUE_UTILISE_GO',
            'LIMITE_FICHIERS_OUVERTS', 'LIMITE_PROCESSUS',
            'SERVICES_TCP_INDISPONIBLES', 'DNS_LATENCE', 'LOG_LIGNES',
            'LOG_LIGNES_MATCH', 'FICHIER_EXISTE', 'FICHIER_TAILLE',
            'TEMPERATURE_MAX', 'VENTILATEUR_RPM', 'MODBUS_VALEUR',
            'BANDE_PASSANTE', 'LATENCE', 'TAUX_ERREUR', 'DISPONIBILITE'
        )),
    valeur numeric(18,4) not null,
    unite varchar(20),
    horodatage timestamp(6) not null,
    primary key (id)
);

create table metriques_horaires (
    id bigint generated by default as identity,
    equipement_id uuid not null,
    type_metrique varchar(40) not null
        check (type_metrique in (
            'CPU', 'RAM', 'DISQUE', 'SWAP', 'NOMBRE_PROCESSUS', 'PORTS_ECOUTE',
            'DISQUE_IO_LECTURE', 'DISQUE_IO_ECRITURE', 'RESEAU_IO_ENTRANT',
            'RESEAU_IO_SORTANT', 'UPTIME', 'CHARGE_1MIN', 'RAM_TOTALE_MO',
            'RAM_UTILISEE_MO', 'DISQUE_TOTAL_GO', 'DISQUE_UTILISE_GO',
            'LIMITE_FICHIERS_OUVERTS', 'LIMITE_PROCESSUS',
            'SERVICES_TCP_INDISPONIBLES', 'DNS_LATENCE', 'LOG_LIGNES',
            'LOG_LIGNES_MATCH', 'FICHIER_EXISTE', 'FICHIER_TAILLE',
            'TEMPERATURE_MAX', 'VENTILATEUR_RPM', 'MODBUS_VALEUR',
            'BANDE_PASSANTE', 'LATENCE', 'TAUX_ERREUR', 'DISPONIBILITE'
        )),
    heure timestamp(6) not null,
    moyenne numeric(18,4),
    minimum numeric(18,4),
    maximum numeric(18,4),
    nombre_mesures bigint not null,
    primary key (id),
    constraint uk_metrique_horaire unique (equipement_id, type_metrique, heure)
);

create table metriques_journalieres (
    id bigint generated by default as identity,
    equipement_id uuid not null,
    type_metrique varchar(40) not null
        check (type_metrique in (
            'CPU', 'RAM', 'DISQUE', 'SWAP', 'NOMBRE_PROCESSUS', 'PORTS_ECOUTE',
            'DISQUE_IO_LECTURE', 'DISQUE_IO_ECRITURE', 'RESEAU_IO_ENTRANT',
            'RESEAU_IO_SORTANT', 'UPTIME', 'CHARGE_1MIN', 'RAM_TOTALE_MO',
            'RAM_UTILISEE_MO', 'DISQUE_TOTAL_GO', 'DISQUE_UTILISE_GO',
            'LIMITE_FICHIERS_OUVERTS', 'LIMITE_PROCESSUS',
            'SERVICES_TCP_INDISPONIBLES', 'DNS_LATENCE', 'LOG_LIGNES',
            'LOG_LIGNES_MATCH', 'FICHIER_EXISTE', 'FICHIER_TAILLE',
            'TEMPERATURE_MAX', 'VENTILATEUR_RPM', 'MODBUS_VALEUR',
            'BANDE_PASSANTE', 'LATENCE', 'TAUX_ERREUR', 'DISPONIBILITE'
        )),
    jour date not null,
    moyenne numeric(18,4),
    minimum numeric(18,4),
    maximum numeric(18,4),
    nombre_mesures bigint not null,
    primary key (id),
    constraint uk_metrique_journaliere unique (equipement_id, type_metrique, jour)
);

-- === seuil ===

create table seuils_alerte (
    id uuid not null,
    type_metrique varchar(40) not null
        check (type_metrique in (
            'CPU', 'RAM', 'DISQUE', 'SWAP', 'NOMBRE_PROCESSUS', 'PORTS_ECOUTE',
            'DISQUE_IO_LECTURE', 'DISQUE_IO_ECRITURE', 'RESEAU_IO_ENTRANT',
            'RESEAU_IO_SORTANT', 'UPTIME', 'CHARGE_1MIN', 'RAM_TOTALE_MO',
            'RAM_UTILISEE_MO', 'DISQUE_TOTAL_GO', 'DISQUE_UTILISE_GO',
            'LIMITE_FICHIERS_OUVERTS', 'LIMITE_PROCESSUS',
            'SERVICES_TCP_INDISPONIBLES', 'DNS_LATENCE', 'LOG_LIGNES',
            'LOG_LIGNES_MATCH', 'FICHIER_EXISTE', 'FICHIER_TAILLE',
            'TEMPERATURE_MAX', 'VENTILATEUR_RPM', 'MODBUS_VALEUR',
            'BANDE_PASSANTE', 'LATENCE', 'TAUX_ERREUR', 'DISPONIBILITE'
        )),
    equipement_id uuid,
    avertissement numeric(18,4),
    critique numeric(18,4),
    duree_secondes integer not null,
    primary key (id),
    constraint uk_seuil_type_equipement unique (type_metrique, equipement_id)
);

-- === alerte ===

create table alertes (
    id uuid not null,
    equipement_id uuid not null,
    type_anomalie varchar(30) not null
        check (type_anomalie in ('INDISPONIBILITE', 'CPU', 'RAM', 'DISQUE', 'RESEAU', 'MATERIEL')),
    severite varchar(20) not null
        check (severite in ('INFO', 'AVERTISSEMENT', 'CRITIQUE')),
    statut varchar(20) not null
        check (statut in ('DECLENCHEE', 'PRISE_EN_COMPTE', 'RESOLUE')),
    date_declenchement timestamp(6) not null,
    date_resolution timestamp(6),
    dernier_rappel timestamp(6),
    utilisateur_prise_en_charge bigint,
    primary key (id)
);

-- === audit ===

create table journal_audit (
    id bigint generated by default as identity,
    utilisateur_id bigint not null,
    action varchar(255) not null,
    horodatage timestamp(6) not null,
    adresse_ip_source varchar(45),
    primary key (id)
);

-- === rapport ===

create table rapports (
    id uuid not null,
    type_rapport varchar(20) not null
        check (type_rapport in ('JOURNALIER', 'HEBDOMADAIRE', 'MENSUEL')),
    periode_debut timestamp(6) not null,
    periode_fin timestamp(6) not null,
    chemin_fichier_pdf varchar(255),
    date_generation timestamp(6) not null,
    primary key (id)
);

-- === index ===

create index idx_alerte_statut on alertes (statut);
create index idx_metrique_equipement_horodatage on metriques (equipement_id, horodatage);
create index idx_metrique_horaire_equipement on metriques_horaires (equipement_id, heure);
create index idx_metrique_journaliere_equipement on metriques_journalieres (equipement_id, jour);

-- === cles etrangeres ===

alter table alertes add constraint fk_alerte_equipement
    foreign key (equipement_id) references equipements;
alter table alertes add constraint fk_alerte_utilisateur_prise_en_charge
    foreign key (utilisateur_prise_en_charge) references app_users;
alter table equipements add constraint fk_equipement_depend_de
    foreign key (depend_de_id) references equipements;
alter table journal_audit add constraint fk_journal_audit_utilisateur
    foreign key (utilisateur_id) references app_users;
alter table metriques add constraint fk_metrique_equipement
    foreign key (equipement_id) references equipements;
alter table password_reset_tokens add constraint fk_password_reset_token_app_user
    foreign key (app_user_id) references app_users;
alter table refresh_tokens add constraint fk_refresh_token_app_user
    foreign key (app_user_id) references app_users;
alter table seuils_alerte add constraint fk_seuil_alerte_equipement
    foreign key (equipement_id) references equipements;
